# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: shipto-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
